In [25]:
import numpy
import math

In [26]:
grid = numpy.zeros((4, 4), dtype=int)
print(grid.flatten())


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [27]:
def move(flattenedGrid, key):
    # temp = grid
    size = int(math.sqrt(len(flattenedGrid)))
    print(size)

    grid = numpy.zeros((size, size), dtype=int)

    for i in range(size):
        grid[i][:] = flattenedGrid[i*size : size*(i + 1)]

    for i in range(size):
        flipped = False
        if key in 'lr':  # nếu nhập vào là l hoặc r thì lấy hàng
            row = grid[i, :]
        else:
            row = grid[:, i]  # u hoăc d thì lấy cột

        if key in 'rd':  # nếu là r hoặc d thì lật ngược list để có thể tận dụng hàm get num
            flipped = True
            row = row[::-1]

        notZeros = _get_num(row)  # list những số != 0 trong hàng
        newRow = numpy.zeros_like(row)  # tạo một hàng mới chỉ chứa số 0 có kích cỡ giống hàng cũ
        newRow[:len(notZeros)] = notZeros  # gắn các giá trị != 0 vào mảng mới

        if flipped:
            newRow = newRow[::-1]

        if key in 'lr':
            grid[i, :] = newRow
        else:
            grid[:, i] = newRow

    return grid.flatten()

def _get_num(row):
    notZeros = row[row != 0]
    res = []
    skip = False
    for i in range(len(notZeros)):
        if skip:
            skip = False
            continue
        if i != len(notZeros) - 1 and notZeros[i] == notZeros[i + 1]:  # nếu 2 số liền nhau mà giống nhau thì cộng lại và cho vào mảng mới
            sum = notZeros[i] * 2
            res.append(sum)
            skip = True
        else:
            res.append(notZeros[i])
    return res

In [28]:
test = numpy.full((4,4), 2)

test3 = [1,1,1,1]

test[0][:] = test3[0:4]
print(test)

[[1 1 1 1]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [57]:
grid = numpy.array([
    [2,0,4,0],
    [2,0,4,5],
    [2,0,4,5],
    [2,0,4,5]
    ])

grid2 = numpy.array([2,0,9,8,0])

# unoccupied_pos = list(zip(*numpy.where(grid2 == 0)))
unoccupied_pos = list(*numpy.where(grid2 == 0))


print(unoccupied_pos)
print(*grid2)
# for i in unoccupied_pos:
# print(grid[(0,1)])

[1, 4]
2 0 9 8 0


In [ ]:
maxValPos = list(*numpy.where(grid2 == max(grid2)))