In [62]:
import numpy

In [63]:
grid = numpy.zeros((4, 4), dtype=int)
print(grid.flatten())


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [64]:
def swipeGrid2(flattenedGrid, key):
    # temp = grid
    grid = numpy.zeros((4, 4), dtype=int)

    for i in range(4):
        grid[i,:] = flattenedGrid[i*4:i*4+4]

    temp = grid

    # grid = flattenedGrid
    # temp = flattenedGrid

    for i in range(4):
        flipped = False
        if key in 'lr':  # nếu nhập vào là l hoặc r thì lấy hàng
            this_row = grid[i, :]
        else:
            this_row = grid[:, i]  # u hoăc d thì lấy cột

        if key in 'rd':  # nếu là r hoặc d thì lật ngược list để có thể tận dụng hàm get num
            flipped = True
            this_row = this_row[::-1]

        this_n = _get_num(this_row)  # list những số != 0 trong hàng
        # print(this_n)
        new_this_row = numpy.zeros_like(this_row)  # tạo một hàng mới chỉ chứa số 0 có kích cỡ giống hàng cũ
        new_this_row[:len(this_n)] = this_n  # gắn các giá trị != 0 vào mảng mới

        if flipped:
            new_this_row = new_this_row[::-1]

        if key in 'lr':
            # grid[i, :] = new_this_row
            temp[i, :] = new_this_row
        else:
            # grid[:, i] = new_this_row
            temp[:, i] = new_this_row

    return temp.flatten()

def _get_num(row):
    this_n = row[row != 0]
    res = []
    skip = False
    for i in range(len(this_n)):
        if skip:
            skip = False
            continue
        if i != len(this_n) - 1 and this_n[i] == this_n[i + 1]:  # nếu 2 số liền nhau mà giống nhau thì cộng lại và cho vào mảng mới
            sum = this_n[i] * 2
            res.append(sum)
            skip = True
        else:
            res.append(this_n[i])
    return res

In [73]:
test = numpy.full((4,4), 2)

test3 = [1,1,1,1]

test[0][:] = test3[0:4]
print(test)

[[1 1 1 1]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [66]:
test2 = [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
print(test2)

SyntaxError: invalid syntax (3754652472.py, line 1)

In [69]:
print(swipeGrid2(test.flatten(), 'l'))

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed